export type Lesson = {
  title: string;
  purpose: string;
  targets: string[];
  sections: { heading: string; text?: string; points?: string[] }[];
  standard: string;
  kitchen: string[];
  check: string[];
  evidence: string;
};

export type UnitContent = {
  title: string;
  course: "Culinary Arts 1" | "Culinary Arts 2";
  summary: string;
  essentialQuestion: string;
  enduring: string[];
  vocabulary: string[];
  lessons: Lesson[];
};

const lesson = (
  title: string, purpose: string, targets: string[], sections: Lesson["sections"],
  standard: string, kitchen: string[], check: string[], evidence: string
): Lesson => ({title,purpose,targets,sections,standard,kitchen,check,evidence});

export const unitContent: UnitContent[] = [
  {
    title:"Professional Kitchen Readiness", course:"Culinary Arts 1",
    summary:"Build the safety, sanitation, communication, knife, and lab habits that every later kitchen experience will require.",
    essentialQuestion:"How do professionals prepare themselves, their stations, and their teams for safe, controlled kitchen work?",
    enduring:["Professional trust is earned through preparation, communication, responsibility, and follow-through.","Safety and sanitation are actions used during production, not rules left on a page.","A complete lab includes planning, mise en place, production, evaluation, costing, reflection, and closeout.","Control, accuracy, and consistency come before speed."],
    vocabulary:["professional trust","hazard","corrective action","cross-contamination","cross-contact","sanitize","mise en place","yield","portion cost","quality standard"],
    lessons:[
      lesson("Day 1 — Welcome to a Professional Kitchen","Learn how this course works and what it means to earn professional trust.",
        ["Explain how the Field Manual and Google Classroom work together.","Describe professional trust through observable actions.","Recognize the daily writing and laboratory routines.","Identify how Culinary Arts 1 and 2 build toward independent work."],
        [{heading:"Your two course tools",points:["The Field Manual is our discussion, demonstration, review, study, and lab-preparation tool.","Google Classroom is where assignments, submissions, feedback, and due dates live.","Daily writing asks you to use evidence from the previous class; the first day is the exception.","Return to the Field Manual before, during, and after kitchen work instead of treating it as a one-time reading."]},{heading:"Professional trust",text:"A professional kitchen depends on people being able to trust one another. Trust grows when you arrive ready, listen, communicate, report problems, complete your part, protect the team, and leave the station ready for the next group."},{heading:"The course cycle",text:"Learn the standard, watch the technique, plan the work, practice with support, produce, evaluate the evidence, reflect, and improve the next attempt."}],
        "Professionalism is visible in what you prepare, communicate, complete, report, and improve.",
        ["Open the correct Field Manual unit before discussion begins.","Ask questions when a direction or standard is unclear.","Use daily writing to connect one class experience to the next."],
        ["What are the different jobs of the Field Manual and Google Classroom?","What actions allow a kitchen team to trust your work?","Why does reflection belong in a culinary course?"],
        "Day 1 writing and a personal explanation of one professional habit you want to develop."),
      lesson("Day 2 — Physical Safety: See It, Stop It, Report It","Recognize physical hazards and choose the safest immediate response.",
        ["Identify cut, burn, fire, chemical, slip, trip, and fall hazards.","Separate prevention from immediate corrective action.","Decide when work must stop.","Explain why prompt reporting protects the whole kitchen."],
        [{heading:"The safety decision",points:["See it: name the exact unsafe condition and where it is located.","Stop it: pause the affected work and prevent other people from entering the hazard.","Correct it: take only an action you are trained and authorized to take.","Report it: tell the instructor immediately about injuries, damaged equipment, fire, chemical exposure, or any condition you cannot safely control."]},{heading:"Common physical hazards",points:["Cuts: unstable boards, hidden knives, damaged blades, unsafe carrying, or distracted cutting.","Burns and fire: wet towels, unprotected hot surfaces, unsafe handles, steam, combustibles, or unattended heat.","Chemicals: unlabeled containers, products near food, incorrect concentration, or mixed cleaners.","Slips, trips, and falls: spills, cords, open doors, clutter, blocked aisles, or unsafe lifting."]},{heading:"Use the posted procedure",text:"School-specific emergency, injury, evacuation, and reporting directions control the response. Do not improvise first aid or attempt equipment or fire responses you have not been trained and directed to perform."}],
        "No product, deadline, or cleanup task is more important than stopping and reporting an uncontrolled hazard.",
        ["Scan the route and station before beginning work.","Use clear warnings such as “hot,” “sharp,” “behind,” and “spill.”","Keep emergency exits, aisles, and safety equipment accessible."],
        ["What is the difference between preventing a hazard and correcting one?","Which conditions require work to stop immediately?","Why is reporting a mistake a professional action?"],
        "Professional-kitchen image inspection, incident-card decision, or instructor safety observation."),
      lesson("Day 3 — Personal Hygiene and the Handwashing Investigation","Prepare yourself for food work and test what effective handwashing requires.",
        ["Complete a ready-to-work self-check.","Identify moments when hands must be washed.","Demonstrate the complete handwashing process.","Use illness reporting and gloves correctly."],
        [{heading:"Ready to work",points:["Wear the required clothing, closed-toe nonslip shoes, and effective hair restraint.","Store personal items in the assigned location.","Cover and report cuts or wounds as directed.","Report symptoms or diagnoses that may affect food safety before handling food.","Wash hands before touching food, equipment, or sanitized food-contact surfaces."]},{heading:"Effective handwashing",points:["Wet hands with running water and apply soap.","Scrub every surface—including fingertips, between fingers, thumbs, wrists, and around nails—for at least 20 seconds.","Rinse under running water and dry with the approved single-use method.","Avoid recontaminating clean hands when leaving the handwashing area.","Put on gloves only after hands are clean and dry."]},{heading:"Glow Germ investigation",text:"Three volunteers compare different handwashing approaches. The class observes what remains, identifies commonly missed areas, and uses the evidence to explain why time alone does not guarantee complete handwashing."},{heading:"Gloves and illness",text:"Gloves never replace handwashing. Change them when torn, contaminated, or used for a new task. Illness reporting protects classmates and guests; it is not something to hide or work through."}],
        "A student is not ready for food work until personal readiness, illness reporting, and handwashing requirements are met.",
        ["Wash again after any contamination moment.","Keep hands away from hair, face, phones, and personal items during food work.","Use a tasting utensil only once."],
        ["What did the handwashing investigation make visible?","When must gloves be changed?","Why is illness reporting a team responsibility?"],
        "Glow Germ observation notes, handwashing demonstration, or readiness self-check."),
      lesson("Day 4 — Contamination and Controls","Protect food by identifying how contamination moves and placing controls in the workflow.",
        ["Distinguish biological, chemical, and physical contamination.","Distinguish cross-contamination from allergen cross-contact.","Explain cleaning versus sanitizing.","Design a workstation that separates clean and contaminated tasks."],
        [{heading:"Three contamination types",points:["Biological: harmful bacteria, viruses, parasites, fungi, or toxins.","Chemical: cleaners, sanitizers, pesticides, or unsafe metals entering food.","Physical: glass, metal, packaging, hair, or another foreign object entering food."]},{heading:"Two kinds of transfer",text:"Cross-contamination transfers harmful microorganisms. Allergen cross-contact transfers an allergen protein into food that should not contain it. Both require prevention, separation, honest communication, and a complete reset when control is lost."},{heading:"Clean, then sanitize",points:["Cleaning removes food and soil.","Rinsing removes loosened soil and detergent.","Sanitizing reduces microorganisms on the already-clean surface.","Air-drying protects the sanitized surface from being recontaminated by a towel."]},{heading:"Station control",points:["Separate dirty, raw, ready-to-eat, and finished-food zones.","Control tools, boards, towels, gloves, tasting utensils, and waste.","Keep chemicals labeled and away from ingredients.","Stop, explain what was affected, and reset the complete pathway when contamination may have occurred."]},{heading:"The nine major allergens",text:"Milk, eggs, fish, crustacean shellfish, tree nuts, peanuts, wheat, soybeans, and sesame. Never promise that food is allergen-free without an approved process and verified ingredients."}],
        "Safe production depends on preventing transfer, recognizing when control is lost, and completing the full corrective action.",
        ["Build separation into the station before food arrives.","Clean and sanitize between incompatible tasks.","Ask and verify instead of guessing about an allergen."],
        ["How is cross-contamination different from cross-contact?","Why can a surface be clean but not sanitized?","What must be reset after a contamination event?"],
        "Contamination-control plan, station diagram, or scenario response."),
      lesson("Day 5 — Hazard Stations: Inspect, Correct, Teach","Combine the first week’s safety ideas and teach one professional-kitchen situation accurately.",
        ["Inspect a complete kitchen scene systematically.","Prioritize hazards by possible harm and urgency.","Explain the correction and the prevention for each problem.","Teach findings clearly and respond to questions."],
        [{heading:"Your team’s station process",points:["Observe the whole image before deciding what is wrong.","Name each hazard precisely and point to the evidence.","Classify the hazard and explain what harm could occur.","Choose the immediate corrective action and the habit or setup that would prevent it.","Decide which hazard must be addressed first and defend that choice.","Prepare every team member to explain part of the station."]},{heading:"A strong teach-back",text:"A teach-back does more than list mistakes. It explains the evidence, possible harm, immediate correction, and future prevention in language classmates can use during kitchen work."},{heading:"Listen across stations",text:"Each group is responsible for one scene, but every student is responsible for learning from all of them. Record patterns that repeat across knife, heat, chemical, traffic, hygiene, and contamination situations."}],
        "Safety knowledge is useful only when you can recognize a condition, communicate it, and choose an appropriate control.",
        ["Assign speaking and evidence roles before presenting.","Use the image—not a guess—to support each claim.","Correct inaccurate information before the class moves on."],
        ["Which hazard at your station had the highest priority, and why?","What was the difference between your correction and prevention?","Which safety pattern appeared in more than one scene?"],
        "Completed hazard-station record and team teach-back."),
      lesson("Day 6 — Knife and Salsa Demonstration: Watch the Whole Lab Cycle","See how a professional lab moves from a standardized recipe to a controlled closeout.",
        ["Identify each stage of the recurring lab cycle.","Observe safe knife setup, grip, guide hand, and movement.","Connect measurements and knife cuts to usable mise en place.","Explain how storage, labeling, and closeout protect the next day’s work."],
        [{heading:"The recurring lab cycle",points:["Read: understand the purpose, yield, ingredients, equipment, procedure, safety, allergens, and quality standard.","Plan: identify roles, sequence, controls, and the finished-product goal.","Prepare: build a stable station and complete measured mise en place.","Produce: follow the method, communicate, and record actual work.","Verify and evaluate: compare safety, yield, waste, taste, texture, appearance, and consistency to the standard.","Close and reflect: package, label, store, clean, sanitize, inspect, and identify the next improvement."]},{heading:"Knife control",points:["Stabilize the board and inspect the knife.","Use a secure pinch grip and protected guide-hand claw.","Create a stable surface on the ingredient before continuing.","Cut with a controlled motion and keep the knife visible when pausing.","Carry one knife at a time, point down, with a clear “sharp” warning.","Never place a knife in a sink or beneath another object."]},{heading:"Watch for decisions",text:"The demonstration is not a cooking show. Notice why the instructor selects each tool, cut, container, label, storage location, and cleaning action—and what would happen if that control were skipped."}],
        "A demonstration is successful when students can explain the decisions and reproduce the process safely—not merely remember what the finished food looked like.",
        ["Keep the recipe and lab packet open during the demonstration.","Record questions about sequence, cuts, measurements, or closeout.","Do not handle knives or ingredients until your team is authorized."],
        ["Which decisions happened before the first cut?","How does a knife cut affect salsa quality?","What must happen before mise en place can be stored?"],
        "Demonstration notes and the team’s initial Salsa Fresca lab plan."),
      lesson("Day 7 — Salsa Production 1: Build Controlled Mise en Place","Turn the demonstration into safe, measured, usable team production.",
        ["Pass the station-readiness check.","Read the recipe and assign useful team roles.","Measure accurately and complete assigned knife cuts safely.","Record usable product, trim, waste, packaging, labeling, and storage."],
        [{heading:"Before cutting",points:["Read the entire recipe and confirm the assigned batch.","Identify safety and allergen controls.","Gather only the equipment required for the current work.","Set a stable board, inspect knives, and prepare labeled storage containers.","Assign roles while keeping every student responsible for the full team result."]},{heading:"Production records matter",text:"Record what actually happens: ingredient amounts, usable mise en place, trim or waste, unfinished work, storage location, label information, and any change from the plan. These records become the evidence used for costing and evaluation."},{heading:"Day 1 closeout",points:["Stop production with enough time to package safely.","Label and date every stored component as directed.","Return food promptly to approved storage.","Wash, rinse, sanitize, and air-dry equipment and surfaces.","Inspect the station from the next team’s point of view."]}],
        "Usable mise en place is safely cut, accurately measured, protected from contamination, labeled, stored, and supported by an honest production record.",
        ["Accuracy before speed.","Keep knives, boards, towels, containers, and waste under control.","Report and record any deviation instead of hiding it."],
        ["What made your station ready before cutting began?","Which measurement or cut required the most control?","What information must appear in the production record?"],
        "Salsa Fresca planning page, Production Day 1 record, and stored mise en place."),
      lesson("Day 8 — Salsa Production 2: Assemble, Season, and Store","Finish the knife work and turn separate ingredients into a consistent finished salsa.",
        ["Reopen and verify stored mise en place safely.","Complete remaining measurements and knife cuts.","Assemble and season through controlled tasting.","Measure finished volume and complete packaging, labeling, storage, and closeout."],
        [{heading:"Restart safely",points:["Verify labels, dates, storage condition, and product quality before using yesterday’s work.","Reset the station and assign today’s sequence.","Complete any remaining cuts or measurements to the required standard.","Keep finished product separated from dirty tools and waste."]},{heading:"Controlled assembly and seasoning",points:["Follow the recipe sequence before making adjustments.","Mix thoroughly enough to distribute ingredients without damaging texture.","Taste only when authorized, using a clean utensil once.","Identify what the product needs, make one small change, mix, and taste again.","Record adjustments so the decision can be evaluated later."]},{heading:"Finish the record",text:"Measure the total finished volume, determine the number of usable portions, record remaining waste, and note any difference between planned and actual yield before packaging and storage."}],
        "The finished salsa is safe, balanced, appropriately textured, consistent, measurable, and supported by a complete production record.",
        ["Use the quality standard before adjusting seasoning.","Protect the finished product during cleanup.","Complete closeout before the team considers production finished."],
        ["How did yesterday’s storage affect today’s restart?","Why change only one seasoning variable at a time?","What actual data will be needed for costing?"],
        "Production Day 2 record, finished Salsa Fresca, yield measurement, and closeout inspection."),
      lesson("Day 9 — Taste, Evaluate, and Cost","Use sensory and production evidence to judge quality, yield, waste, and cost.",
        ["Compare fresh and day-stored salsa fairly.","Evaluate taste, texture, appearance, consistency, and storage effects.","Use package price and recipe quantity to calculate ingredient and batch cost.","Connect yield, portion size, and waste to a production recommendation."],
        [{heading:"A fair product comparison",points:["Use the same quality categories for both samples.","Describe specific evidence instead of saying only “good” or “bad.”","Separate personal preference from whether the product met its intended standard.","Identify which differences likely came from storage time, ingredient behavior, cut size, seasoning, or team process."]},{heading:"Guided costing",points:["Find the usable cost of each recipe quantity from the package price and package amount.","Add ingredient costs to find total batch cost.","Divide the batch cost by the number of usable portions to find portion cost.","Use the production record—not an imagined perfect yield—for actual calculations."]},{heading:"Production decisions",text:"A professional evaluation ends with a decision. Recommend what should remain the same, what should change, and how the change would affect quality, waste, labor, yield, or portion cost."}],
        "Evaluation uses observable product evidence and honest production data to improve the next batch.",
        ["Taste safely and record observations before team discussion changes your first evidence.","Show calculations with labels and units.","Check whether the numerical answer is realistic."],
        ["What changed between the fresh and stored samples?","How did waste affect actual cost per portion?","What is the most useful change for the next batch?"],
        "Completed sensory comparison, guided costing, costing summary, and production recommendation."),
      lesson("Day 10 — Kitchen Readiness Standards: Use Evidence","Return to the opening standards and prove where they appeared during the Salsa Fresca cycle.",
        ["Identify evidence of safety, sanitation, organization, technique, quality, and professionalism.","Distinguish participation from demonstrated skill.","Name a specific success and a useful next step.","Transfer the hazard-analysis process from a professional kitchen to a home kitchen."],
        [{heading:"Evidence, not impressions",points:["Safety and sanitation: identify a control you actually used.","Planning and organization: show where the recipe, roles, mise en place, timing, or records guided the team.","Technical execution: name a measurement, knife, storage, or closeout skill.","Product quality: use sensory or yield evidence.","Professionalism: describe communication, responsibility, feedback, or follow-through.","Reflection: explain one correction that would improve the next attempt."]},{heading:"From professional to home kitchens",text:"The same thinking used in our kitchen images and salsa lab can help younger students inspect a home kitchen: locate the unsafe condition, explain possible harm, choose the immediate correction, and identify the habit that prevents it."},{heading:"Challenge Book launch",text:"Your team will receive one home-kitchen safety category and begin planning a realistic scene with eight distinct, visible hazards for a sixth-grade audience."}],
        "A strong reflection names the action, cites the evidence, explains the result, and identifies a realistic next step.",
        ["Use the lab packet, product observations, and team experience as evidence.","Do not award yourself credit for an action you cannot describe.","Carry corrections into the next lab instead of leaving them on the reflection page."],
        ["What evidence best shows your current kitchen readiness?","Which standard needs the most practice?","How does the professional-kitchen inspection prepare you for the home-kitchen project?"],
        "Individual kitchen-readiness reflection and initial Home Kitchen Safety Challenge plan."),
      lesson("Day 11 — Home Kitchen Safety Challenge Book","Create an accurate visual safety challenge that sixth-grade students can investigate.",
        ["Plan exactly eight different hazards within one assigned category.","Write a precise AI image prompt from visible scene facts.","Evaluate and revise the generated image for accuracy and clarity.","Build a teacher answer key from the exact same challenge image."],
        [{heading:"The six team categories",points:["Knife safety.","Stove, oven, and heat safety.","Counter and appliance clutter.","Sink and chemical safety.","Refrigerator and food storage.","Cross-contamination and handwashing."]},{heading:"Plan before generating",points:["Build one realistic, age-appropriate home-kitchen scene.","For each hazard, specify what is unsafe, where it appears, and what visual clue makes it identifiable.","Explain what harm could occur, the immediate correction, and the prevention habit.","Check that all eight hazards are genuinely different and collectively cover the assigned category."]},{heading:"The challenge image",text:"The student-facing image contains exactly the eight planned hazards. It includes no answers, labels, numbers, arrows, circles, injury, logos, watermarks, corrective actions, or distracting extra hazards."},{heading:"The teacher answer key",points:["Duplicate the exact approved challenge image; do not regenerate the scene.","Add numbered circles over the eight hazard locations.","Provide a matching written key for every circle.","For each item, include the location and problem, hazard type, why it matters, correction, and prevention."]},{heading:"Use AI as a production tool",text:"Your planning controls the content. After generation, compare the result to all eight planned hazards, remove or revise accidental extra hazards, and confirm that every answer-key circle points to the exact same image students will inspect."},{heading:"Project timing",text:"This lesson launches the class book. The approved images and answer keys may be finalized later before the sixth-grade kitchens begin after Thanksgiving; Unit 2 does not need to wait for final book assembly."}],
        "The finished challenge is accurate, realistic, injury-free, age-appropriate, visually clear, and useful to a sixth-grade learner and teacher.",
        ["Use the completed stove, oven, and heat-safety sample as a quality model—not a prompt to copy.","Keep possible harm, correction, and prevention in the written key rather than the image prompt.","Verify all eight hazards and all eight circles before submission."],
        ["Why must the answer key use the exact same image?","What belongs in the written key but not the image prompt?","How will your team detect an accidental ninth hazard?"],
        "Team scene plan, final AI prompt, clean challenge image, numbered answer-key image, written key, and reflection.")
    ]
  },
  {
    title:"Bread, Fermentation, Grains & Pasta", course:"Culinary Arts 1",
    summary:"Learn how measurement, mixing, time, and heat turn simple ingredients into breads, grains, and pasta.",
    essentialQuestion:"How do measurement, mixing, time, and heat build structure?",
    enduring:["Baking rewards precision.","Fermentation is alive and must be judged by the dough, not only by the clock.","Grains and pasta require method-specific texture standards.","Resting can hydrate ingredients and relax gluten."],
    vocabulary:["gluten","fermentation","proof","knead","hydration","al dente","pilaf","risotto"],
    lessons:[
      lesson("Baking Foundations & Quick Breads","Small measurement and mixing errors create large changes in baked products.",
        ["Explain the functions of major baking ingredients.","Distinguish muffin, biscuit, and creaming methods.","Prevent overmixing.","Evaluate volume, crumb, color, texture, and doneness."],
        [{heading:"Ingredient functions",points:["Flour builds structure; liquid hydrates starch and proteins.","Fat tenderizes and carries flavor; sugar sweetens, browns, tenderizes, and holds moisture.","Eggs add structure, richness, color, emulsification, and leavening.","Salt controls flavor and strengthens structure; chemical leaveners produce gas."]},{heading:"Mixing methods",points:["Muffin method: combine dry and wet mixtures separately, then mix only until combined.","Biscuit method: cut cold fat into dry ingredients, add liquid, and handle gently.","Creaming method: beat fat and sugar to trap air before adding remaining ingredients."]},{heading:"Troubleshooting",text:"Tough quick breads often come from overmixing or excess flour. Low volume can come from expired leavener, inaccurate measurement, or incorrect mixing."}],
        "Use weight when assigned, follow the mixing method, and stop mixing when the required structure has formed.",
        ["Preheat and prepare pans before mixing.","Keep biscuit fat cold.","Check doneness in the correct location."],
        ["Why is accurate measurement especially important in baking?","How do the muffin and creaming methods differ?","Why can overmixing toughen a quick bread?"],
        "Product-quality evaluation comparing waffles/pancakes, biscuits, or banana bread."),
      lesson("Yeast, Fermentation & Dough Development","Yeast activity changes with temperature, time, sugar, salt, hydration, and dough strength.",
        ["Describe fermentation.","Develop and assess gluten.","Judge proofing from dough evidence.","Diagnose dense or poorly browned bread."],
        [{heading:"Control points",points:["Confirm yeast is active and ingredients are at the assigned temperature.","Mix and knead until the dough reaches the required development.","Protect fermentation temperature and time.","Shape without destroying all internal gas.","Proof until the dough shows assigned readiness signs.","Bake for structure, color, and internal doneness."]},{heading:"Diagnose before blaming",text:"Dense bread may result from weak development, underproofing, inactive yeast, or poor fermentation control. Excessive salt can slow yeast; excessive heat can damage it; insufficient time can limit gas production."}],
        "The clock guides the process, but the condition of the dough determines readiness.",
        ["Record dough temperature or room conditions when directed.","Compare dough before and after fermentation.","Evaluate crust, crumb, volume, aroma, and internal doneness."],
        ["What conditions influence fermentation?","How can you tell that dough is developed?","Why should proofing not be judged by time alone?"],
        "Fermentation notes and product evaluation from pizza dough, focaccia, naan, or cinnamon rolls."),
      lesson("Grains, Starches & Fresh Pasta","Ingredient knowledge helps preserve quality and reduce waste.",
        ["Select a grain method.","Prepare pasta to an appropriate texture.","Make, rest, roll, and cut fresh pasta.","Evaluate hydration and doneness."],
        [{heading:"Method-specific standards",points:["Steamed or boiled rice: tender grains with appropriate separation.","Risotto: creamy surrounding texture with correctly cooked grains.","Polenta or grits: smooth, fully hydrated, and seasoned.","Potatoes: texture appropriate to variety and method.","Pasta: tender with slight firmness when appropriate, never mushy."]},{heading:"Fresh pasta process",points:["Measure flour and eggs accurately.","Develop a smooth, elastic dough.","Rest to relax gluten and hydrate flour.","Roll gradually to prevent tearing.","Cut uniformly and protect from sticking.","Cook briefly and evaluate before draining."]}],
        "Texture must match the ingredient, method, and intended dish.",
        ["Salt cooking water as directed.","Taste for doneness before draining.","Reserve useful cooking liquid when the formula requires it."],
        ["What distinguishes risotto from steamed rice?","Why is pasta dough rested?","What makes pasta al dente?"],
        "Fresh-pasta process record or grain-method quality comparison.")
    ]
  },
  {
    title:"Nutrition, Flavor & Kitchen Mathematics", course:"Culinary Arts 1",
    summary:"Taste with purpose. Use nutrition and kitchen math to make food that is balanced, safe, and realistic.",
    essentialQuestion:"How do you make food safe, balanced, appropriate, and realistic?",
    enduring:["Flavor combines taste, aroma, texture, temperature, appearance, and sound.","Seasoning is a controlled process of tasting, identifying, adjusting, and retasting.","Never guess about an allergy.","Cost, value, nutrition, and quality are related but not interchangeable."],
    vocabulary:["umami","aroma","seasoning","AP","EP","yield percent","portion cost","conversion factor"],
    lessons:[
      lesson("Taste, Flavor & Controlled Seasoning","Seasoning should make food taste more like itself, not simply taste salty.",
        ["Distinguish taste from flavor.","Identify sweet, sour, salty, bitter, and umami.","Adjust one variable at a time.","Evaluate balance in relation to the intended dish."],
        [{heading:"Taste and flavor",text:"Taste receptors detect sweet, sour, salty, bitter, and umami. Aroma comes through the nose. Flavor combines taste with aroma, texture, temperature, appearance, and sound."},{heading:"Controlled adjustment",points:["Taste only when safe and permitted, using a clean utensil once.","Identify what is missing: salt, acid, sweetness, depth, aroma, or texture.","Make one small adjustment.","Mix, allow the adjustment to distribute, and taste again.","Record the useful change when consistency matters."]},{heading:"Balance is contextual",text:"A curry, soup, bread, sauce, and dessert do not share one universal balance. Evaluate whether flavor is appropriate to the dish and culinary tradition."}],
        "Diagnose before adding. One controlled change gives useful evidence; several changes at once hide the cause.",
        ["Use a tasting plan.","Name the problem before selecting the correction.","Compare the final flavor to the product goal."],
        ["How is taste different from flavor?","Why adjust one variable at a time?","What can acid change besides sourness?"],
        "Flavor-adjustment log or before-and-after sensory evaluation."),
      lesson("Nutrition, Dietary Needs & Allergen Responsibility","Plan food that is safe, appropriate, and satisfying.",
        ["Identify nutrient categories.","Recognize common dietary needs.","Explain how cooking choices affect nutrition.","Communicate honestly about ingredients and allergens."],
        [{heading:"Nutrient categories",points:["Carbohydrates provide energy, fiber, and food structure.","Protein supports growth, repair, enzymes, and structure.","Fat provides energy, flavor, vitamins, and cell function.","Vitamins and minerals support body processes and regulation.","Water supports hydration, temperature control, and transport."]},{heading:"Planning considerations",points:["Vegetarian and vegan choices require checking hidden ingredients.","Gluten-related restrictions require attention to wheat, barley, rye, labels, and shared equipment.","Lactose tolerance varies and alternatives perform differently.","Religious and cultural practices deserve accurate, respectful planning.","Food allergies require cross-contact prevention and verified ingredients."]},{heading:"Never guess",text:"When you do not know, say that you do not know and ask the instructor or responsible supervisor. Confidence without verification is dangerous."}],
        "An adaptation must remain safe, satisfying, and honest about what it contains.",
        ["Review labels before production.","Identify shared-equipment risks.","Evaluate whether an adaptation still meets the dish’s purpose."],
        ["How can a cooking method change nutrition?","Why are ingredient substitutions not always equivalent?","What should you say when you cannot verify an allergen question?"],
        "Recipe allergen analysis or a justified dietary adaptation."),
      lesson("Yield, Portions, Cost & Menu Decisions","Kitchen mathematics connects ingredients to the real production plan.",
        ["Use common conversions.","Differentiate as-purchased and edible-portion quantities.","Calculate yield percent and portion cost.","Explain how cost affects menu decisions."],
        [{heading:"Core formulas",points:["Conversion factor = desired yield ÷ original yield.","New quantity = original quantity × conversion factor.","Yield percent = edible portion ÷ as-purchased quantity × 100.","Cost per portion = total recipe cost ÷ portions produced."]},{heading:"AP and EP",text:"As-purchased quantity includes trim and waste. Edible portion is the usable amount. Ten pounds of carrots producing eight pounds of usable carrots has an 80% yield."},{heading:"Cost and value",text:"A low-cost dish can still be a poor choice if it wastes labor, equipment capacity, time, or ingredients. A professional plan considers the entire operation."},{heading:"Menu performance",text:"A star is high popularity/high contribution; a plowhorse is high/low; a puzzle is low/high; and a dog is low/low. These labels support analysis, not automatic decisions."}],
        "Show the calculation, label the unit, and test whether the result is realistic.",
        ["Verify yield before scaling.","Use realistic portion sizes.","Recheck equipment capacity after changing batch size."],
        ["What is the difference between AP and EP?","How do you calculate cost per portion?","Why is lowest ingredient cost not always best value?"],
        "Scaled formula, yield test, virtual-shopping sheet, or portion-cost analysis.")
    ]
  },
  {
    title:"Proteins & Eggs", course:"Culinary Arts 1",
    summary:"Cook eggs and proteins safely while building the texture, flavor, and doneness the dish needs.",
    essentialQuestion:"How does the protein tell you which method and doneness it needs?",
    enduring:["Quality and safety are separate checks.","Connective tissue, fat, thickness, and tenderness influence method selection.","Egg proteins change quickly under heat.","Resting and carryover cooking affect final doneness."],
    vocabulary:["fabrication","coagulation","emulsion","brine","carryover cooking","connective tissue"],
    lessons:[
      lesson("Protein Selection, Fabrication & Method","Choose a method based on the product rather than habit.",
        ["Identify quality and storage considerations.","Prevent contamination during fabrication.","Match tenderness and structure to a cooking method.","Verify safe temperature and dish-appropriate quality."],
        [{heading:"Match product to method",points:["Tender cuts: fast dry heat such as sauté, grill, roast, or broil.","More connective tissue: combination methods such as braise or stew.","Ground products: careful sanitation and required final temperature.","Delicate fish: gentle sauté, poach, steam, or bake.","Large roasts or whole poultry: even heat, correct thermometer placement, and resting."]},{heading:"Safe fabrication",points:["Keep raw product and ready-to-eat food separate.","Use clean, sanitized tools and boards.","Return product to temperature control promptly.","Do not wash raw poultry in the sink.","Clean and sanitize after fabrication."]},{heading:"Safety and quality",text:"A protein may reach a safe temperature and still be dry, tough, greasy, or poorly seasoned. Professional performance requires both checks."}],
        "Use the required thermometer location and temperature while also protecting texture, moisture, seasoning, and presentation.",
        ["Plan the raw-product workflow.","Use separate quality and safety checkpoints.","Account for resting and carryover."],
        ["Why should raw poultry not be washed?","How does connective tissue affect method selection?","Why are safety and quality evaluated separately?"],
        "Protein method justification, temperature log, or product-quality evaluation."),
      lesson("Brining, Breading & Frying Control","Layer technique while controlling moisture, adhesion, oil, and final temperature.",
        ["Explain how brining changes seasoning and moisture.","Build an organized breading station.","Control oil temperature and batch size.","Evaluate crust, interior moisture, and safety."],
        [{heading:"Brine control",text:"Concentration, contact time, product size, and temperature matter. Keep poultry under safe temperature control and follow the standardized formula."},{heading:"Breading system",points:["Prepare dry, wet, and final coating stages in order.","Keep one hand dry and one hand wet when practical.","Coat completely without heavy clumps.","Rest breaded product when directed."]},{heading:"Frying",points:["Do not overload the fryer or pan.","Monitor oil temperature between batches.","Lower food safely and never add water to hot oil.","Verify internal temperature and drain without trapping steam."]}],
        "The coating should adhere and brown while the interior remains moist and reaches the required safe temperature.",
        ["Sequence the station before touching raw poultry.","Track oil recovery between batches.","Avoid cross-contaminating finished product."],
        ["How can an overloaded batch affect quality?","Why separate wet and dry breading work?","What evidence shows both safety and quality?"],
        "Chicken-nugget production record with temperatures and quality notes."),
      lesson("Egg Functions, Coagulation & Custards","Control temperature to protect texture and safety.",
        ["Explain egg functions.","Prepare eggs using controlled heat.","Prevent curdling and overcoagulation.","Use eggs to structure, bind, thicken, coat, leaven, or emulsify."],
        [{heading:"Egg functions",points:["Structure in cakes, custards, and mixtures.","Emulsification in mayonnaise and hollandaise.","Leavening in foams and sponge products.","Binding in breaded or shaped foods.","Coating in egg wash and breading.","Thickening in custards and sauces.","Color and richness in pasta and baked goods."]},{heading:"Heat control",text:"Egg proteins coagulate as they heat. Excess temperature or time squeezes out moisture and creates curdling, toughness, or weeping. Gentle, even heat and correct doneness indicators protect texture."}],
        "Finished egg products meet both their temperature requirement and their intended texture.",
        ["Use gentle heat for delicate egg products.","Temper when combining eggs with hot liquid.","Remove products with carryover cooking in mind."],
        ["What is coagulation?","How do eggs function in an emulsion?","Why can high heat damage a custard?"],
        "Crème brûlée or egg-technique evaluation explaining heat control.")
    ]
  },
  {
    title:"Stocks, Soups, Sauces & Emulsions", course:"Culinary Arts 2",
    summary:"Build flavor in layers. Use stocks, herbs, spices, thickening, and finishing to create soups and sauces.",
    essentialQuestion:"How do you build flavor in layers and finish it with control?",
    enduring:["A simmer extracts differently from a boil.","Sauce consistency must suit its use.","Herbs and spices require timing and control.","Emulsions depend on ratio, temperature, and gradual incorporation."],
    vocabulary:["stock","broth","roux","slurry","reduction","liaison","emulsion","aromatics","mother sauce"],
    lessons:[
      lesson("Herbs, Spices & Aromatic Flavor Building","Build flavor in layers so each ingredient has a clear job.",
        ["Distinguish herbs, spices, and aromatics.","Choose whole, ground, fresh, or dried forms.","Control bloom, toast, steep, and finishing timing.","Avoid muddy or overpowering flavor."],
        [{heading:"Forms and timing",points:["Fresh delicate herbs are often added late.","Hardy herbs can tolerate longer cooking.","Whole spices release gradually and may need removal.","Ground spices release quickly and can burn.","Toasting or blooming in fat can develop aroma when controlled."]},{heading:"Build in layers",text:"Aromatics establish the base; herbs and spices add identity; stock or liquid carries flavor; reduction concentrates; finishing salt, acid, fat, or fresh herbs completes balance."}],
        "Seasoning should support the dish, not overpower it. Taste, identify, adjust, and taste again.",
        ["Smell and identify before adding.","Record amount and timing.","Taste after adequate distribution time."],
        ["Why might delicate herbs be added late?","What happens when ground spices burn?","How does fat affect spice aroma?"],
        "Spice comparison, mulled-cider analysis, or documented seasoning adjustment."),
      lesson("Stocks, Broths & Flavor Extraction","A controlled simmer extracts flavor while protecting clarity and quality.",
        ["Differentiate stock and broth.","Identify white, brown, vegetable, and fish stocks.","Use simmering, skimming, and straining procedures.","Cool and store safely."],
        [{heading:"Stock families",points:["White stock: bones and aromatics without deep browning.","Brown stock: browned bones and aromatics.","Vegetable stock: vegetables and aromatics with shorter extraction.","Fish stock or fumet: delicate bones and aromatics cooked briefly.","Broth: flavorful liquid often made with meat and suitable for direct service."]},{heading:"Control points",points:["Start with the formula’s assigned temperature and ratio.","Maintain a simmer rather than a violent boil.","Skim impurities as directed.","Strain without forcing solids through.","Cool rapidly using the approved method, label, date, and store."]}],
        "Finished stock has clean, appropriate flavor and body and has been handled safely from extraction through cooling.",
        ["Avoid unnecessary stirring.","Keep solids submerged as directed.","Record cooling controls."],
        ["How does stock differ from broth?","Why can boiling cloud a stock?","Why does fish stock use a shorter extraction?"],
        "Chicken-stock process record or stock-quality evaluation."),
      lesson("Soups, Mother Sauces & Thickening","Use the correct system to create the intended body, flavor, and finish.",
        ["Classify soups.","Identify the five mother sauces.","Select a thickener.","Diagnose consistency and flavor."],
        [{heading:"Soup categories",text:"Clear, thickened, purée, chowder, specialty or regional, and cold soups each require different body and finishing standards."},{heading:"Mother sauces",points:["Béchamel: milk and white roux.","Velouté: light stock and roux.","Espagnole: brown stock, brown roux, and aromatics.","Tomato: tomato base and aromatics.","Hollandaise: warm egg-yolk and butter emulsion."]},{heading:"Thickening systems",points:["Roux: cooked fat and flour.","Slurry: starch dispersed in cold liquid.","Reduction: evaporation concentrates body and flavor.","Purée: vegetables, legumes, or starch provide body.","Liaison: egg yolk and cream finish carefully.","Emulsion: technique suspends fat and liquid."]}],
        "Body, seasoning, temperature, and garnish fit the soup or sauce and its intended use.",
        ["Cook roux to the assigned stage.","Add slurry gradually and allow starch to cook.","Evaluate formula-specific consistency."],
        ["How does a roux differ from a slurry?","Name the five mother sauces.","Why does reduction change both body and flavor?"],
        "Béchamel, red sauce, or chicken-noodle-soup evaluation."),
      lesson("Emulsions & Sauce Repair","Temperature, ratio, and gradual incorporation determine whether liquids remain combined.",
        ["Explain temporary and stable emulsions.","Build mayonnaise safely.","Recognize a broken emulsion.","Use a controlled repair when appropriate."],
        [{heading:"How emulsions work",text:"An emulsion disperses one liquid in another liquid that normally separates. An emulsifier helps stabilize droplets. Adding fat too quickly, using poor ratios, or losing temperature control can break the system."},{heading:"Prevention and repair",points:["Begin with ingredients at the assigned temperature.","Add the dispersed phase slowly while mixing continuously.","Stop and diagnose at the first sign of separation.","Repair with a fresh base only when the approved method permits it."]}],
        "The sauce is smooth, stable for its intended service, properly seasoned, and handled safely.",
        ["Control addition rate.","Watch texture instead of following time blindly.","Keep raw-egg products under the approved safety procedure."],
        ["What causes an emulsion to break?","Why is gradual incorporation important?","Why is prevention easier than repair?"],
        "Mayonnaise production notes or emulsion troubleshooting record.")
    ]
  },
  {
    title:"Fruits, Vegetables, Potatoes & Dairy", course:"Culinary Arts 2",
    summary:"Choose the right method for each ingredient and protect its color, texture, flavor, and value.",
    essentialQuestion:"How do you stop cooking when the ingredient is at its best?",
    enduring:["The ingredient’s structure and intended result determine the method.","Uniform cuts support even cooking and portioning.","Blanching and shocking separate partial cooking from final service.","Dairy requires temperature control to prevent scorching, curdling, and separation."],
    vocabulary:["blanch","shock","purée","curdle","cultured dairy","yield"],
    lessons:[
      lesson("Produce Selection, Cuts & Method","Protect quality and reduce waste from receiving through service.",
        ["Evaluate produce quality.","Choose cuts and methods.","Protect color, texture, and nutrients.","Use trim responsibly."],
        [{heading:"Quality goals",points:["Protect color by avoiding unnecessary overcooking.","Protect texture with a method suited to the ingredient’s structure.","Reduce waste through careful trimming and usable trim recovery.","Develop flavor with roast, sauté, grill, steam, braise, or blanch methods.","Improve presentation with consistent cuts and portions."]},{heading:"Method decision",text:"Consider density, water content, natural sugar, desired browning, final texture, service timing, and whether the product will be cooked again."}],
        "Cook produce to the texture the dish needs—not simply until it becomes soft.",
        ["Wash before cutting.","Separate usable trim as directed.","Taste at multiple points to identify the correct stopping point."],
        ["How does cut size affect cooking?","Why can overcooking dull color?","List three ways to reduce vegetable waste."],
        "Produce yield record or method comparison."),
      lesson("Blanching, Shocking, Potatoes & Starches","Control partial cooking, color, texture, and later service.",
        ["Explain blanching and shocking.","Prepare an ice bath correctly.","Choose potato methods by variety and desired texture.","Prevent waterlogging or uneven cooking."],
        [{heading:"Blanch and shock",text:"Blanching briefly cooks food in boiling water. Shocking cools it rapidly in ice water to stop cooking. The process can set color, partially cook vegetables, loosen skins, or prepare food for later service. Drain and store safely afterward."},{heading:"Potato control",points:["Choose a variety suited to the method.","Cut uniformly.","Start in the assigned water temperature.","Control agitation to prevent breakdown.","Drain and dry when the next method requires browning."]}],
        "Partial cooking stops at the intended stage and the product is cooled, drained, and stored correctly.",
        ["Have the ice bath ready before blanching.","Do not overload the water.","Label products prepared for later service."],
        ["What is the purpose of shocking?","Why must blanched food be drained?","How does potato variety affect method?"],
        "Blanch/shock process check or pumpkin-gnocchi texture analysis."),
      lesson("Milk, Cream, Butter, Cheese & Cultured Dairy","Use heat and acidity carefully to protect dairy texture.",
        ["Identify dairy products and uses.","Prevent scorching and curdling.","Select cheese for melting or finishing.","Compare dairy and plant-based alternatives."],
        [{heading:"Control points",points:["Milk: avoid scorching and maintain cold storage.","Cream: control reduction and do not overwhip.","Butter: understand smoke point and prevent burning.","Cheese: match melting behavior to the dish.","Cultured dairy: add carefully because acid and high heat can curdle.","Plant-based alternatives: check allergens and performance differences."]},{heading:"Fresh cheese",text:"Acid and heat can coagulate milk proteins. Curds must be handled gently, drained to the intended moisture, seasoned appropriately, and cooled safely."}],
        "Dairy contributes the intended richness, structure, acidity, or texture without scorching, greasiness, or unwanted separation.",
        ["Use moderate heat and stir where the formula directs.","Watch the product’s texture, not only temperature.","Store finished dairy products promptly."],
        ["Why can cultured dairy curdle?","What controls whipped-cream texture?","How does acid help create fresh ricotta?"],
        "Fresh-ricotta process record or dairy troubleshooting reflection.")
    ]
  },
  {
    title:"Pastry, Cookies, Cakes & Advanced Baking", course:"Culinary Arts 2",
    summary:"Use precise mixing, temperature, shaping, baking, and cooling to create tender pastries and baked goods.",
    essentialQuestion:"How do small, precise choices create tenderness, lift, and a clean finish?",
    enduring:["Different products need different kinds of structure.","Temperature controls fat behavior and spread.","Overmixing can create toughness or tunneling.","A product is not finished until it has cooled, set, and been evaluated."],
    vocabulary:["lamination","creaming","aeration","custard","blind bake","tenderness"],
    lessons:[
      lesson("Cookies & Creaming","Control aeration, spread, texture, portion, and doneness.",
        ["Use the creaming method.","Portion consistently.","Control dough and pan temperature.","Diagnose spread and toughness."],
        [{heading:"Control points",points:["Use fat at the assigned temperature.","Cream only to the required aeration.","Add eggs gradually and scrape the bowl.","Mix flour only until incorporated.","Portion uniformly on cool prepared pans.","Remove at dish-appropriate doneness and cool before moving."]},{heading:"Troubleshooting",text:"Excessive spreading may come from warm dough, too much fat or sugar, weak flour structure, or hot pans. Tough texture often comes from overmixing or excess flour."}],
        "Cookies are uniform in size, spread, color, texture, and doneness.",
        ["Check pan temperature between batches.","Use a consistent scoop or weight.","Compare edge and center doneness."],
        ["How does fat temperature affect spread?","Why can hot pans create inconsistency?","What causes toughness?"],
        "Chocolate-chip or gingerbread cookie batch comparison."),
      lesson("Pie Dough, Fillings & Pastry","Limit gluten while controlling fat, water, rest, shape, and final bake.",
        ["Use the pie-dough method.","Recognize correct hydration.","Rest and roll without stretching.","Prepare and evaluate fillings."],
        [{heading:"Pie dough method",points:["Keep fat at the assigned temperature.","Cut fat into flour to the required size.","Add only enough cold liquid for the dough to hold.","Mix minimally and rest before rolling.","Roll evenly and transfer without stretching.","Chill or blind bake as directed."]},{heading:"Troubleshooting",text:"Tough crust often comes from too much water or gluten development. Shrinking can come from overworking, insufficient rest, or stretching dough in the pan."},{heading:"Filling control",text:"Balance fruit, sugar, acid, starch, and moisture so the filling sets without becoming pasty or flooding the crust."}],
        "The crust is tender, baked through, properly shaped, and appropriate to the filling.",
        ["Keep tools and ingredients cool.","Avoid adding flour carelessly during rolling.","Vent, dock, weight, or seal according to the product."],
        ["Why does pie dough rest?","What causes shrinking?","How does filling moisture affect crust?"],
        "Pie-dough handling record and finished-crust evaluation."),
      lesson("Cakes, Custards, Creams & Finishing","Build and set aerated or egg-thickened structures without overworking or overheating them.",
        ["Control cake aeration and mixing.","Prepare pastry cream safely.","Whip cream to an intended stage.","Evaluate structure, crumb, smoothness, and finish."],
        [{heading:"Cake structure",text:"Low volume can come from poor aeration, expired leavener, or incorrect mixing. Tunnels often indicate overmixing or incorrect oven temperature."},{heading:"Custard and pastry cream",points:["Measure starch, sugar, eggs, and dairy accurately.","Temper eggs when directed.","Cook long enough to thicken and remove raw starch flavor.","Prevent scorching with controlled heat and mixing.","Cool rapidly with surface protection."]},{heading:"Whipped cream",text:"Cold cream and equipment support aeration. Stop at the intended peak; overwhipping moves toward graininess and butter."}],
        "The finished component has the intended volume, set, smoothness, sweetness, and service stability.",
        ["Prepare cooling space before cooking custard.","Scrape bowls during mixing.","Finish only after components reach the correct temperature."],
        ["What causes cake tunnels?","Why is pastry cream cooled with surface protection?","How can whipped cream be overworked?"],
        "Cheesecake, pastry-cream, crème brûlée, or finishing-component evaluation."),
      lesson("Fried & Yeasted Pastry","Combine fermentation, shaping, frying, draining, and finishing without losing structure.",
        ["Develop and proof enriched dough.","Shape consistently.","Control frying temperature.","Finish at the correct stage."],
        [{heading:"Production control",points:["Develop the dough while accounting for fat and sugar.","Ferment and proof from product evidence.","Shape to even thickness and size.","Fry in controlled batches.","Drain before glazing or coating.","Evaluate interior doneness as well as exterior color."]}],
        "The product is evenly shaped, fully cooked, not greasy, and finished cleanly.",
        ["Track oil temperature.","Avoid overcrowding.","Use a cooling and finishing sequence that does not trap excess oil."],
        ["Why can enriched dough ferment differently?","What makes fried dough greasy?","Why is color alone not enough to judge doneness?"],
        "Donut or cinnamon-roll production reflection.")
    ]
  },
  {
    title:"Global Culinary Applications", course:"Culinary Arts 2",
    summary:"Bring your skills together to plan, cook, serve, and reflect on food made for a real audience.",
    essentialQuestion:"How do you use your course skills to do responsible work for a real audience?",
    enduring:["Authentic work combines several competencies for someone beyond the instructor.","Cultural responsibility requires research and avoids careless stereotypes.","Hospitality never overrides safety.","Reflection uses specific evidence to improve the next performance."],
    vocabulary:["authentic recipient","hospitality","sustainability","production plan","portfolio evidence","capstone"],
    lessons:[
      lesson("Global Foodways & Cultural Responsibility","Prepare food connected to a culinary tradition with accuracy, curiosity, and respect.",
        ["Research origin and context.","Identify ingredients and techniques.","Distinguish adaptation from misrepresentation.","Explain decisions with sources."],
        [{heading:"Responsible inquiry",points:["Locate credible information about place, people, history, ingredients, and service.","Avoid presenting one dish as if it represents an entire culture.","Name adaptations honestly.","Use respectful language and verify unfamiliar claims.","Let culinary technique and evidence lead the explanation."]},{heading:"Application",text:"Coconut curry chicken and guajillo-braised chicken tacos demonstrate layered aromatics, spice handling, protein method, sauce development, timing, and cultural research. The recipe is a starting point for study, not the whole story of a cuisine."}],
        "Use research to explain the dish accurately. Name adaptations honestly, and do not treat one dish as an entire culture.",
        ["Connect each major ingredient or method to research.","Document substitutions.","Evaluate dish-appropriate quality rather than one familiar standard."],
        ["Why can one dish not represent an entire culture?","How should an adaptation be described?","What makes a source useful?"],
        "Research notes, source list, or menu explanation."),
      lesson("Sustainability, Hospitality & Service","Use resources responsibly while caring for the recipient’s experience.",
        ["Reduce avoidable waste.","Use water and energy responsibly.","Communicate with guests respectfully.","Respond professionally to delays, feedback, and problems."],
        [{heading:"Sustainable student actions",points:["Purchase and gather realistic quantities.","Label, date, rotate, and protect food.","Trim carefully and portion accurately.","Use equipment at appropriate capacity.","Keep oven and refrigerator doors closed.","Track what is discarded and why."]},{heading:"Hospitality moments",points:["Greet and acknowledge promptly.","Listen, confirm details, and avoid assumptions.","Verify allergy questions; do not guess.","Communicate delays honestly.","Listen to complaints without arguing and involve the responsible supervisor.","Verify packaging, labels, quantities, and condition before pickup or delivery."]},{heading:"Non-negotiable",text:"Never serve unsafe food, hide an allergen risk, skip a required check, or ignore policy simply to make a guest happy."}],
        "The recipient receives safe, accurate, timely, respectful service and the operation accounts for its resources.",
        ["Assign a final product verifier.","Track leftovers and avoidable waste.","Debrief both food quality and recipient experience."],
        ["How is waste prevention different from waste disposal?","What should happen when service is delayed?","Why can hospitality never override safety?"],
        "Waste record, service checklist, client feedback, or event debrief."),
      lesson("Global Menu Student-Designed Culinary Capstone","Demonstrate course learning through one realistic dish for an authentic recipient.",
        ["Research and propose a dish.","Standardize and scale the recipe.","Plan ingredients, equipment, timing, safety, and quality.","Produce, evaluate, and reflect with evidence."],
        [{heading:"Ten phases",points:["Selection: choose a realistic dish tied to a culinary tradition and course skills.","Research: document origin, context, ingredients, methods, and sources.","Proposal: identify recipient, method, timeline, safety controls, and resources.","Recipe work: standardize and calculate yield.","Ingredient plan: submit a department-funded request; families are not required to purchase ingredients.","Production plan: sequence mise en place, cooking, holding, plating, cleanup, and timing.","Safety plan: control temperature, contamination, allergens, and equipment.","Production: execute within the approved late-spring window.","Evaluation: assess taste, texture, appearance, safety, organization, and dish-appropriate quality.","Reflection: explain decisions, evidence, feedback, and next steps."]},{heading:"Success criteria",points:["Safety and sanitation meet the required standard.","The plan is realistic and materials are ready.","Techniques are applied correctly with growing independence.","Taste, texture, appearance, and doneness fit the dish.","Research is culturally responsible.","Communication, cleanup, and response to feedback are professional.","Reflection cites specific evidence."]},{heading:"Critical standard",text:"A strong final product cannot cancel a serious safety failure. Safety, sanitation, and essential technical execution must each meet the required standard."}],
        "Essential categories must meet the course proficiency standard; the finished product is only one part of the evidence.",
        ["Work backward from the production deadline.","Confirm every critical control before production.","Retain approved evidence without interrupting safe work."],
        ["Who is the authentic recipient?","Which taught competencies does the dish demonstrate?","What evidence will support the final reflection?"],
        "Proposal, research, standardized recipe, cost/yield work, production plan, safety plan, final evaluation, feedback, and reflection.")
    ]
  }
];
